// Content Studio Phase 3A, brief sections 12-14 (VideoScript,
// VisualBrief, CaptionPackage) plus PlatformVariant. No video or image
// is generated by anything in this file — these are structured
// specifications only, consumed by a real generation provider in a
// future phase.
import { validateContentHook, type ContentHook } from "./contentIdea.contract.js";
import { asObject, optionalString, requireArrayOf, requireBoolean, requireNumber, requireString, requireStringArray } from "./contractValidation.util.js";

// ---------------------------------------------------------------------------
// PlatformVariant — a generic, extensible per-platform rendering.
// Deliberately not one hardcoded field per platform (no
// "instagramCaption"/"facebookCaption"/"tiktokCaption" trio) so a
// future platform can be added without a contract change, and so
// platform BEHAVIOUR (hashtag count/style, tone) comes from retrieved
// PLATFORM_RULE knowledge rather than being baked into this shape
// (brief section 26's own "do not hard code stereotypes" rule).
// ---------------------------------------------------------------------------

export const PLATFORMS = ["INSTAGRAM", "FACEBOOK", "TIKTOK"] as const;
export type Platform = (typeof PLATFORMS)[number];

const PLATFORM_VARIANT_CONTRACT = "PlatformVariant";

export interface PlatformVariant {
  platform: Platform;
  caption: string;
  hashtags: string[];
  callToAction: string;
}

export function validatePlatformVariant(raw: unknown): PlatformVariant {
  const obj = asObject(raw, PLATFORM_VARIANT_CONTRACT);
  const platform = requireString(obj, "platform", PLATFORM_VARIANT_CONTRACT);
  if (!(PLATFORMS as readonly string[]).includes(platform)) {
    throw new Error(`${PLATFORM_VARIANT_CONTRACT}.platform: expected one of ${PLATFORMS.join(", ")}.`);
  }
  return {
    platform: platform as Platform,
    caption: requireString(obj, "caption", PLATFORM_VARIANT_CONTRACT),
    hashtags: requireStringArray(obj, "hashtags", PLATFORM_VARIANT_CONTRACT),
    callToAction: requireString(obj, "callToAction", PLATFORM_VARIANT_CONTRACT),
  };
}

// ---------------------------------------------------------------------------
// CaptionPackage — brief section 14. A master caption plus one
// PlatformVariant per requested platform; deliberately never one
// caption blindly copied to every platform (brief's own explicit
// instruction).
// ---------------------------------------------------------------------------

const CAPTION_PACKAGE_CONTRACT = "CaptionPackage";

export interface CaptionPackage {
  masterCaption: string;
  platformVariants: PlatformVariant[];
  callToAction: string;
  hashtags: string[];
  destinationUrl: string | null;
}

export function validateCaptionPackage(raw: unknown): CaptionPackage {
  const obj = asObject(raw, CAPTION_PACKAGE_CONTRACT);
  return {
    masterCaption: requireString(obj, "masterCaption", CAPTION_PACKAGE_CONTRACT),
    platformVariants: requireArrayOf(obj, "platformVariants", (item) => validatePlatformVariant(item), CAPTION_PACKAGE_CONTRACT),
    callToAction: requireString(obj, "callToAction", CAPTION_PACKAGE_CONTRACT),
    hashtags: requireStringArray(obj, "hashtags", CAPTION_PACKAGE_CONTRACT),
    destinationUrl: optionalString(obj, "destinationUrl", CAPTION_PACKAGE_CONTRACT),
  };
}

// ---------------------------------------------------------------------------
// VideoScript — brief section 12. No video is generated; this is the
// structured specification a future video-generation provider (or a
// human) would work from.
// ---------------------------------------------------------------------------

const VIDEO_SCRIPT_CONTRACT = "VideoScript";
const SCENE_CONTRACT = "VideoScriptScene";

export interface VideoScriptScene {
  sceneNumber: number;
  durationSeconds: number;
  visual: string;
  action: string;
  cameraDirection: string | null;
  voiceover: string | null;
  onScreenText: string | null;
}

function validateScene(raw: unknown): VideoScriptScene {
  const obj = asObject(raw, SCENE_CONTRACT);
  return {
    sceneNumber: requireNumber(obj, "sceneNumber", SCENE_CONTRACT),
    durationSeconds: requireNumber(obj, "durationSeconds", SCENE_CONTRACT),
    visual: requireString(obj, "visual", SCENE_CONTRACT),
    action: requireString(obj, "action", SCENE_CONTRACT),
    cameraDirection: optionalString(obj, "cameraDirection", SCENE_CONTRACT),
    voiceover: optionalString(obj, "voiceover", SCENE_CONTRACT),
    onScreenText: optionalString(obj, "onScreenText", SCENE_CONTRACT),
  };
}

export interface VideoScript {
  title: string;
  duration: number;
  hook: ContentHook;
  scenes: VideoScriptScene[];
  // The full combined voiceover across every scene, and the single
  // most important on-screen text (e.g. the opening title card) —
  // brief section 12 lists both as top-level fields distinct from each
  // scene's own optional voiceover/onScreenText, which this reads as a
  // script-level summary rather than a duplicate of per-scene detail.
  voiceover: string;
  onScreenText: string;
  productReference: string | null;
  callToAction: string;
}

export function validateVideoScript(raw: unknown): VideoScript {
  const obj = asObject(raw, VIDEO_SCRIPT_CONTRACT);
  return {
    title: requireString(obj, "title", VIDEO_SCRIPT_CONTRACT),
    duration: requireNumber(obj, "duration", VIDEO_SCRIPT_CONTRACT),
    hook: validateContentHook(obj.hook),
    scenes: requireArrayOf(obj, "scenes", (item) => validateScene(item), VIDEO_SCRIPT_CONTRACT),
    voiceover: requireString(obj, "voiceover", VIDEO_SCRIPT_CONTRACT),
    onScreenText: requireString(obj, "onScreenText", VIDEO_SCRIPT_CONTRACT),
    productReference: optionalString(obj, "productReference", VIDEO_SCRIPT_CONTRACT),
    callToAction: requireString(obj, "callToAction", VIDEO_SCRIPT_CONTRACT),
  };
}

// ---------------------------------------------------------------------------
// VisualBrief — brief section 13. Never vague ("make a nice video") by
// construction: every field below is required, so an incomplete brief
// fails validation rather than silently reaching a future generation
// provider.
// ---------------------------------------------------------------------------

const VISUAL_BRIEF_CONTRACT = "VisualBrief";

export interface VisualBrief {
  subject: string;
  environment: string;
  composition: string;
  cameraPosition: string;
  cameraMovement: string;
  lighting: string;
  visualStyle: string;
  action: string;
  emotion: string;
  pacing: string;
  aspectRatio: string;
  duration: number;
  brandDirection: string;
  realProductRequired: boolean;
  // Real ProductImage/DigitalAsset ids to source genuine product
  // imagery from — empty when realProductRequired is false. Existence
  // is validated one layer up, same discipline as ContentIdea.productId
  // (see contentIdea.contract.ts's own comment).
  productAssetIds: string[];
  textOverlayRequirements: string;
  continuityRequirements: string;
  negativeInstructions: string;
  safetyRequirements: string;
}

export function validateVisualBrief(raw: unknown): VisualBrief {
  const obj = asObject(raw, VISUAL_BRIEF_CONTRACT);
  return {
    subject: requireString(obj, "subject", VISUAL_BRIEF_CONTRACT),
    environment: requireString(obj, "environment", VISUAL_BRIEF_CONTRACT),
    composition: requireString(obj, "composition", VISUAL_BRIEF_CONTRACT),
    cameraPosition: requireString(obj, "cameraPosition", VISUAL_BRIEF_CONTRACT),
    cameraMovement: requireString(obj, "cameraMovement", VISUAL_BRIEF_CONTRACT),
    lighting: requireString(obj, "lighting", VISUAL_BRIEF_CONTRACT),
    visualStyle: requireString(obj, "visualStyle", VISUAL_BRIEF_CONTRACT),
    action: requireString(obj, "action", VISUAL_BRIEF_CONTRACT),
    emotion: requireString(obj, "emotion", VISUAL_BRIEF_CONTRACT),
    pacing: requireString(obj, "pacing", VISUAL_BRIEF_CONTRACT),
    aspectRatio: requireString(obj, "aspectRatio", VISUAL_BRIEF_CONTRACT),
    duration: requireNumber(obj, "duration", VISUAL_BRIEF_CONTRACT),
    brandDirection: requireString(obj, "brandDirection", VISUAL_BRIEF_CONTRACT),
    realProductRequired: requireBoolean(obj, "realProductRequired", VISUAL_BRIEF_CONTRACT),
    productAssetIds: requireStringArray(obj, "productAssetIds", VISUAL_BRIEF_CONTRACT),
    textOverlayRequirements: requireString(obj, "textOverlayRequirements", VISUAL_BRIEF_CONTRACT),
    continuityRequirements: requireString(obj, "continuityRequirements", VISUAL_BRIEF_CONTRACT),
    negativeInstructions: requireString(obj, "negativeInstructions", VISUAL_BRIEF_CONTRACT),
    safetyRequirements: requireString(obj, "safetyRequirements", VISUAL_BRIEF_CONTRACT),
  };
}
